(function(e, a) { for(var i in a) e[i] = a[i]; }(exports, /******/ (function(modules) { // webpackBootstrap
/******/ 	// The module cache
/******/ 	var installedModules = {};
/******/
/******/ 	// The require function
/******/ 	function __webpack_require__(moduleId) {
/******/
/******/ 		// Check if module is in cache
/******/ 		if(installedModules[moduleId]) {
/******/ 			return installedModules[moduleId].exports;
/******/ 		}
/******/ 		// Create a new module (and put it into the cache)
/******/ 		var module = installedModules[moduleId] = {
/******/ 			i: moduleId,
/******/ 			l: false,
/******/ 			exports: {}
/******/ 		};
/******/
/******/ 		// Execute the module function
/******/ 		modules[moduleId].call(module.exports, module, module.exports, __webpack_require__);
/******/
/******/ 		// Flag the module as loaded
/******/ 		module.l = true;
/******/
/******/ 		// Return the exports of the module
/******/ 		return module.exports;
/******/ 	}
/******/
/******/
/******/ 	// expose the modules object (__webpack_modules__)
/******/ 	__webpack_require__.m = modules;
/******/
/******/ 	// expose the module cache
/******/ 	__webpack_require__.c = installedModules;
/******/
/******/ 	// define getter function for harmony exports
/******/ 	__webpack_require__.d = function(exports, name, getter) {
/******/ 		if(!__webpack_require__.o(exports, name)) {
/******/ 			Object.defineProperty(exports, name, { enumerable: true, get: getter });
/******/ 		}
/******/ 	};
/******/
/******/ 	// define __esModule on exports
/******/ 	__webpack_require__.r = function(exports) {
/******/ 		if(typeof Symbol !== 'undefined' && Symbol.toStringTag) {
/******/ 			Object.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });
/******/ 		}
/******/ 		Object.defineProperty(exports, '__esModule', { value: true });
/******/ 	};
/******/
/******/ 	// create a fake namespace object
/******/ 	// mode & 1: value is a module id, require it
/******/ 	// mode & 2: merge all properties of value into the ns
/******/ 	// mode & 4: return value when already ns object
/******/ 	// mode & 8|1: behave like require
/******/ 	__webpack_require__.t = function(value, mode) {
/******/ 		if(mode & 1) value = __webpack_require__(value);
/******/ 		if(mode & 8) return value;
/******/ 		if((mode & 4) && typeof value === 'object' && value && value.__esModule) return value;
/******/ 		var ns = Object.create(null);
/******/ 		__webpack_require__.r(ns);
/******/ 		Object.defineProperty(ns, 'default', { enumerable: true, value: value });
/******/ 		if(mode & 2 && typeof value != 'string') for(var key in value) __webpack_require__.d(ns, key, function(key) { return value[key]; }.bind(null, key));
/******/ 		return ns;
/******/ 	};
/******/
/******/ 	// getDefaultExport function for compatibility with non-harmony modules
/******/ 	__webpack_require__.n = function(module) {
/******/ 		var getter = module && module.__esModule ?
/******/ 			function getDefault() { return module['default']; } :
/******/ 			function getModuleExports() { return module; };
/******/ 		__webpack_require__.d(getter, 'a', getter);
/******/ 		return getter;
/******/ 	};
/******/
/******/ 	// Object.prototype.hasOwnProperty.call
/******/ 	__webpack_require__.o = function(object, property) { return Object.prototype.hasOwnProperty.call(object, property); };
/******/
/******/ 	// __webpack_public_path__
/******/ 	__webpack_require__.p = "";
/******/
/******/
/******/ 	// Load entry module and return exports
/******/ 	return __webpack_require__(__webpack_require__.s = 0);
/******/ })
/************************************************************************/
/******/ ({

/***/ "./src/app/app.component.css.shim.ngstyle.js":
/*!***************************************************!*\
  !*** ./src/app/app.component.css.shim.ngstyle.js ***!
  \***************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IiIsImZpbGUiOiJzcmMvYXBwL2FwcC5jb21wb25lbnQuY3NzIn0= */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/app.component.ngfactory.js":
/*!********************************************!*\
  !*** ./src/app/app.component.ngfactory.js ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./app.component.css.shim.ngstyle */ "./src/app/app.component.css.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./topbar/topbar.component.ngfactory */ "./src/app/topbar/topbar.component.ngfactory.js");
var i3 = __webpack_require__(/*! ./topbar/topbar.component */ "./src/app/topbar/topbar.component.ts");
var i4 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var i5 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i6 = __webpack_require__(/*! ./call-server.service */ "./src/app/call-server.service.ts");
var styles_AppComponent = [i0.styles];
var RenderType_AppComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_AppComponent, data: {} });
exports.RenderType_AppComponent = RenderType_AppComponent;
function View_AppComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-topbar", [], null, null, null, i2.View_TopbarComponent_0, i2.RenderType_TopbarComponent)), i1.ɵdid(1, 114688, null, 0, i3.TopbarComponent, [], null, null), (_l()(), i1.ɵeld(2, 0, null, null, 1, "button", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.functionClick() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["CLICK"])), (_l()(), i1.ɵeld(4, 0, null, null, 1, "button", [], null, [[null, "click"]], function (_v, en, $event) { var ad = true; var _co = _v.component; if (("click" === en)) {
        var pd_0 = (_co.functionClick2() !== false);
        ad = (pd_0 && ad);
    } return ad; }, null, null)), (_l()(), i1.ɵted(-1, null, ["CLICK2"]))], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AppComponent_0 = View_AppComponent_0;
function View_AppComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-root", [], null, null, null, View_AppComponent_0, RenderType_AppComponent)), i1.ɵdid(1, 114688, null, 0, i4.AppComponent, [i1.PLATFORM_ID, i5.DOCUMENT, i6.CallServerService], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_AppComponent_Host_0 = View_AppComponent_Host_0;
var AppComponentNgFactory = i1.ɵccf("app-root", i4.AppComponent, View_AppComponent_Host_0, {}, {}, []);
exports.AppComponentNgFactory = AppComponentNgFactory;


/***/ }),

/***/ "./src/app/app.component.ts":
/*!**********************************!*\
  !*** ./src/app/app.component.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var common_1 = __webpack_require__(/*! @angular/common */ "@angular/common");
var environment_1 = __webpack_require__(/*! ../environments/environment */ "./src/environments/environment.ts");
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var call_server_service_1 = __webpack_require__(/*! ./call-server.service */ "./src/app/call-server.service.ts");
var AppComponent = /** @class */ (function () {
    function AppComponent(platformId, document, callServerService) {
        this.platformId = platformId;
        this.document = document;
        this.callServerService = callServerService;
        this.title = 'test-console';
    }
    AppComponent.prototype.ngOnInit = function () {
        this.getData();
        if (!common_1.isPlatformBrowser(this.platformId)) {
            var bases = this.document.getElementsByTagName('base');
            if (bases.length > 0) {
                bases[0].setAttribute('href', environment_1.environment.baseHref);
            }
        }
    };
    AppComponent.prototype.getData = function () {
        this.callServerService.getData().subscribe(function (res) {
            console.log(res);
            // this.data = res;
            // console.log(this.data);
        });
    };
    AppComponent.prototype.functionClick = function () {
        var abc = {
            name: 'thienvu',
            content: '',
            author: '',
            index: 1
        };
        // this.data = abc;
        // this.data[0].author = 'thienvu';
    };
    AppComponent.prototype.functionClick2 = function () {
        console.log(this.data);
    };
    return AppComponent;
}());
exports.AppComponent = AppComponent;


/***/ }),

/***/ "./src/app/app.module.ts":
/*!*******************************!*\
  !*** ./src/app/app.module.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppModule = /** @class */ (function () {
    function AppModule() {
    }
    return AppModule;
}());
exports.AppModule = AppModule;


/***/ }),

/***/ "./src/app/app.server.module.ngfactory.js":
/*!************************************************!*\
  !*** ./src/app/app.server.module.ngfactory.js ***!
  \************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! ./app.server.module */ "./src/app/app.server.module.ts");
var i2 = __webpack_require__(/*! ./app.component */ "./src/app/app.component.ts");
var i3 = __webpack_require__(/*! ./app.component.ngfactory */ "./src/app/app.component.ngfactory.js");
var i4 = __webpack_require__(/*! @angular/common */ "@angular/common");
var i5 = __webpack_require__(/*! @angular/platform-browser */ "@angular/platform-browser");
var i6 = __webpack_require__(/*! @angular/platform-server */ "@angular/platform-server");
var i7 = __webpack_require__(/*! @angular/animations/browser */ "@angular/animations/browser");
var i8 = __webpack_require__(/*! @angular/platform-browser/animations */ "@angular/platform-browser/animations");
var i9 = __webpack_require__(/*! @ng-toolkit/universal */ "@ng-toolkit/universal");
var i10 = __webpack_require__(/*! @nguniversal/common */ "@nguniversal/common");
var i11 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var i12 = __webpack_require__(/*! @angular/http */ "@angular/http");
var i13 = __webpack_require__(/*! @angular/animations */ "@angular/animations");
var i14 = __webpack_require__(/*! @nguniversal/module-map-ngfactory-loader */ "@nguniversal/module-map-ngfactory-loader");
var i15 = __webpack_require__(/*! ./app.module */ "./src/app/app.module.ts");
var AppServerModuleNgFactory = i0.ɵcmf(i1.AppServerModule, [i2.AppComponent], function (_l) { return i0.ɵmod([i0.ɵmpd(512, i0.ComponentFactoryResolver, i0.ɵCodegenComponentFactoryResolver, [[8, [i3.AppComponentNgFactory]], [3, i0.ComponentFactoryResolver], i0.NgModuleRef]), i0.ɵmpd(5120, i0.LOCALE_ID, i0.ɵangular_packages_core_core_k, [[3, i0.LOCALE_ID]]), i0.ɵmpd(4608, i4.NgLocalization, i4.NgLocaleLocalization, [i0.LOCALE_ID, [2, i4.ɵangular_packages_common_common_a]]), i0.ɵmpd(4608, i0.Compiler, i0.Compiler, []), i0.ɵmpd(5120, i0.IterableDiffers, i0.ɵangular_packages_core_core_i, []), i0.ɵmpd(5120, i0.KeyValueDiffers, i0.ɵangular_packages_core_core_j, []), i0.ɵmpd(4608, i5.DomSanitizer, i5.ɵDomSanitizerImpl, [i4.DOCUMENT]), i0.ɵmpd(6144, i0.Sanitizer, null, [i5.DomSanitizer]), i0.ɵmpd(4608, i5.HAMMER_GESTURE_CONFIG, i5.HammerGestureConfig, []), i0.ɵmpd(5120, i5.EVENT_MANAGER_PLUGINS, function (p0_0, p0_1, p0_2, p1_0, p2_0, p2_1, p2_2, p2_3, p3_0) { return [new i5.ɵDomEventsPlugin(p0_0, p0_1, p0_2), new i5.ɵKeyEventsPlugin(p1_0), new i5.ɵHammerGesturesPlugin(p2_0, p2_1, p2_2, p2_3), new i6.ɵangular_packages_platform_server_platform_server_d(p3_0)]; }, [i4.DOCUMENT, i0.NgZone, i0.PLATFORM_ID, i4.DOCUMENT, i4.DOCUMENT, i5.HAMMER_GESTURE_CONFIG, i0.ɵConsole, [2, i5.HAMMER_LOADER], i5.DOCUMENT]), i0.ɵmpd(4608, i5.EventManager, i5.EventManager, [i5.EVENT_MANAGER_PLUGINS, i0.NgZone]), i0.ɵmpd(135680, i5.ɵDomSharedStylesHost, i5.ɵDomSharedStylesHost, [i4.DOCUMENT]), i0.ɵmpd(4608, i5.ɵDomRendererFactory2, i5.ɵDomRendererFactory2, [i5.EventManager, i5.ɵDomSharedStylesHost]), i0.ɵmpd(4608, i6.ɵangular_packages_platform_server_platform_server_c, i6.ɵangular_packages_platform_server_platform_server_c, [i5.DOCUMENT, [2, i5.ɵTRANSITION_ID]]), i0.ɵmpd(6144, i5.ɵSharedStylesHost, null, [i6.ɵangular_packages_platform_server_platform_server_c]), i0.ɵmpd(4608, i6.ɵServerRendererFactory2, i6.ɵServerRendererFactory2, [i5.EventManager, i0.NgZone, i5.DOCUMENT, i5.ɵSharedStylesHost]), i0.ɵmpd(4608, i7.AnimationDriver, i7.ɵNoopAnimationDriver, []), i0.ɵmpd(5120, i7.ɵAnimationStyleNormalizer, i8.ɵangular_packages_platform_browser_animations_animations_c, []), i0.ɵmpd(4608, i7.ɵAnimationEngine, i8.ɵangular_packages_platform_browser_animations_animations_a, [i4.DOCUMENT, i7.AnimationDriver, i7.ɵAnimationStyleNormalizer]), i0.ɵmpd(5120, i0.RendererFactory2, i6.ɵangular_packages_platform_server_platform_server_a, [i6.ɵServerRendererFactory2, i7.ɵAnimationEngine, i0.NgZone]), i0.ɵmpd(4352, i0.Testability, null, []), i0.ɵmpd(4608, i9.ɵa, i9.ɵa, [i0.PLATFORM_ID]), i0.ɵmpd(5120, i9.WINDOW, i9.windowFactory, [i9.ɵa]), i0.ɵmpd(4608, i9.DocumentService, i9.DocumentService, [i0.PLATFORM_ID]), i0.ɵmpd(5120, i9.NGT_DOCUMENT, i9.documentFactory, [i9.DocumentService]), i0.ɵmpd(4608, i9.ɵb, i9.ɵb, [i0.PLATFORM_ID]), i0.ɵmpd(5120, i9.LOCAL_STORAGE, i9.localStorageFactory, [i9.ɵb]), i0.ɵmpd(4608, i5.TransferState, i5.TransferState, []), i0.ɵmpd(4608, i10.ɵTransferHttpCacheInterceptor, i10.ɵTransferHttpCacheInterceptor, [i0.ApplicationRef, i5.TransferState]), i0.ɵmpd(4608, i11.HttpXsrfTokenExtractor, i11.ɵangular_packages_common_http_http_g, [i4.DOCUMENT, i0.PLATFORM_ID, i11.ɵangular_packages_common_http_http_e]), i0.ɵmpd(4608, i11.ɵangular_packages_common_http_http_h, i11.ɵangular_packages_common_http_http_h, [i11.HttpXsrfTokenExtractor, i11.ɵangular_packages_common_http_http_f]), i0.ɵmpd(5120, i11.HTTP_INTERCEPTORS, function (p0_0, p1_0) { return [p0_0, p1_0]; }, [i10.ɵTransferHttpCacheInterceptor, i11.ɵangular_packages_common_http_http_h]), i0.ɵmpd(4608, i11.XhrFactory, i6.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i11.HttpXhrBackend, i11.HttpXhrBackend, [i11.XhrFactory]), i0.ɵmpd(6144, i11.HttpBackend, null, [i11.HttpXhrBackend]), i0.ɵmpd(5120, i11.HttpHandler, i6.ɵangular_packages_platform_server_platform_server_h, [i11.HttpBackend, i0.Injector]), i0.ɵmpd(4608, i11.HttpClient, i11.HttpClient, [i11.HttpHandler]), i0.ɵmpd(4608, i11.ɵangular_packages_common_http_http_d, i11.ɵangular_packages_common_http_http_d, []), i0.ɵmpd(4608, i12.BrowserXhr, i6.ɵangular_packages_platform_server_platform_server_e, []), i0.ɵmpd(4608, i12.ResponseOptions, i12.BaseResponseOptions, []), i0.ɵmpd(4608, i12.XSRFStrategy, i6.ɵangular_packages_platform_server_platform_server_f, []), i0.ɵmpd(4608, i12.XHRBackend, i12.XHRBackend, [i12.BrowserXhr, i12.ResponseOptions, i12.XSRFStrategy]), i0.ɵmpd(4608, i12.RequestOptions, i12.BaseRequestOptions, []), i0.ɵmpd(5120, i12.Http, i6.ɵangular_packages_platform_server_platform_server_g, [i12.XHRBackend, i12.RequestOptions]), i0.ɵmpd(4608, i13.AnimationBuilder, i8.ɵBrowserAnimationBuilder, [i0.RendererFactory2, i5.DOCUMENT]), i0.ɵmpd(4608, i4.ViewportScroller, i4.ɵNullViewportScroller, []), i0.ɵmpd(4608, i0.NgModuleFactoryLoader, i14.ModuleMapNgFactoryLoader, [i0.Compiler, i14.MODULE_MAP]), i0.ɵmpd(5120, i6.BEFORE_APP_SERIALIZED, function (p0_0, p0_1, p0_2) { return [i6.ɵangular_packages_platform_server_platform_server_b(p0_0, p0_1, p0_2)]; }, [i5.DOCUMENT, i0.APP_ID, i5.TransferState]), i0.ɵmpd(1073742336, i4.CommonModule, i4.CommonModule, []), i0.ɵmpd(1024, i0.ErrorHandler, i5.ɵangular_packages_platform_browser_platform_browser_a, []), i0.ɵmpd(256, i0.APP_ID, "app-root", []), i0.ɵmpd(2048, i5.ɵTRANSITION_ID, null, [i0.APP_ID]), i0.ɵmpd(1024, i0.APP_INITIALIZER, function (p0_0, p1_0, p1_1, p1_2) { return [i5.ɵangular_packages_platform_browser_platform_browser_j(p0_0), i5.ɵangular_packages_platform_browser_platform_browser_h(p1_0, p1_1, p1_2)]; }, [[2, i0.NgProbeToken], i5.ɵTRANSITION_ID, i4.DOCUMENT, i0.Injector]), i0.ɵmpd(512, i0.ApplicationInitStatus, i0.ApplicationInitStatus, [[2, i0.APP_INITIALIZER]]), i0.ɵmpd(131584, i0.ApplicationRef, i0.ApplicationRef, [i0.NgZone, i0.ɵConsole, i0.Injector, i0.ErrorHandler, i0.ComponentFactoryResolver, i0.ApplicationInitStatus]), i0.ɵmpd(1073742336, i0.ApplicationModule, i0.ApplicationModule, [i0.ApplicationRef]), i0.ɵmpd(1073742336, i5.BrowserModule, i5.BrowserModule, [[3, i5.BrowserModule]]), i0.ɵmpd(1073742336, i9.NgtUniversalModule, i9.NgtUniversalModule, []), i0.ɵmpd(1073742336, i5.BrowserTransferStateModule, i5.BrowserTransferStateModule, []), i0.ɵmpd(1073742336, i10.TransferHttpCacheModule, i10.TransferHttpCacheModule, []), i0.ɵmpd(1073742336, i11.HttpClientXsrfModule, i11.HttpClientXsrfModule, []), i0.ɵmpd(1073742336, i11.HttpClientModule, i11.HttpClientModule, []), i0.ɵmpd(1073742336, i15.AppModule, i15.AppModule, []), i0.ɵmpd(1073742336, i12.HttpModule, i12.HttpModule, []), i0.ɵmpd(1073742336, i8.NoopAnimationsModule, i8.NoopAnimationsModule, []), i0.ɵmpd(1073742336, i6.ServerModule, i6.ServerModule, []), i0.ɵmpd(1073742336, i14.ModuleMapLoaderModule, i14.ModuleMapLoaderModule, []), i0.ɵmpd(1073742336, i6.ServerTransferStateModule, i6.ServerTransferStateModule, []), i0.ɵmpd(1073742336, i1.AppServerModule, i1.AppServerModule, []), i0.ɵmpd(256, i0.ɵAPP_ROOT, true, []), i0.ɵmpd(256, i11.ɵangular_packages_common_http_http_e, "XSRF-TOKEN", []), i0.ɵmpd(256, i11.ɵangular_packages_common_http_http_f, "X-XSRF-TOKEN", []), i0.ɵmpd(256, i8.ANIMATION_MODULE_TYPE, "NoopAnimations", [])]); });
exports.AppServerModuleNgFactory = AppServerModuleNgFactory;


/***/ }),

/***/ "./src/app/app.server.module.ts":
/*!**************************************!*\
  !*** ./src/app/app.server.module.ts ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var AppServerModule = /** @class */ (function () {
    function AppServerModule() {
    }
    return AppServerModule;
}());
exports.AppServerModule = AppServerModule;


/***/ }),

/***/ "./src/app/call-server.service.ts":
/*!****************************************!*\
  !*** ./src/app/call-server.service.ts ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var http_1 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var operators_1 = __webpack_require__(/*! rxjs/operators */ "rxjs/operators");
var data_model_1 = __webpack_require__(/*! ./data-model */ "./src/app/data-model.ts");
var i0 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i1 = __webpack_require__(/*! @angular/common/http */ "@angular/common/http");
var CallServerService = /** @class */ (function () {
    function CallServerService(http) {
        this.http = http;
    }
    CallServerService.prototype.getData = function () {
        var url = 'http://5a9f973d29d04a00142ff7fe.mockapi.io/api/new';
        return this.http.get(url).pipe(operators_1.map(function (res) {
            return res.map(function (item) { return new data_model_1.DataModel().parseFromResp(item); });
        }));
    };
    CallServerService.ngInjectableDef = i0.defineInjectable({ factory: function CallServerService_Factory() { return new CallServerService(i0.inject(i1.HttpClient)); }, token: CallServerService, providedIn: "root" });
    return CallServerService;
}());
exports.CallServerService = CallServerService;


/***/ }),

/***/ "./src/app/data-model.ts":
/*!*******************************!*\
  !*** ./src/app/data-model.ts ***!
  \*******************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var DataModel = /** @class */ (function () {
    function DataModel(name, content, author, index) {
        this.name = name;
        this.content = content;
        this.author = author;
        this.index = index;
    }
    DataModel.prototype.parseFromResp = function (params) {
        if (params === void 0) { params = {}; }
        this.name = params.name;
        this.content = params.content;
        this.author = params.author;
        this.index = params.index;
        return this;
    };
    return DataModel;
}());
exports.DataModel = DataModel;


/***/ }),

/***/ "./src/app/topbar/topbar.component.ngfactory.js":
/*!******************************************************!*\
  !*** ./src/app/topbar/topbar.component.ngfactory.js ***!
  \******************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var i0 = __webpack_require__(/*! ./topbar.component.scss.shim.ngstyle */ "./src/app/topbar/topbar.component.scss.shim.ngstyle.js");
var i1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var i2 = __webpack_require__(/*! ./topbar.component */ "./src/app/topbar/topbar.component.ts");
var styles_TopbarComponent = [i0.styles];
var RenderType_TopbarComponent = i1.ɵcrt({ encapsulation: 0, styles: styles_TopbarComponent, data: {} });
exports.RenderType_TopbarComponent = RenderType_TopbarComponent;
function View_TopbarComponent_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 36, "section", [], null, null, null, null, null)), (_l()(), i1.ɵeld(1, 0, null, null, 35, "div", [["class", "row"]], null, null, null, null, null)), (_l()(), i1.ɵeld(2, 0, null, null, 11, "div", [["class", "col-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(3, 0, null, null, 10, "div", [["class", "topbar-left"]], null, null, null, null, null)), (_l()(), i1.ɵeld(4, 0, null, null, 9, "ul", [], null, null, null, null, null)), (_l()(), i1.ɵeld(5, 0, null, null, 2, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(6, 0, null, null, 1, "i", [["class", "fa icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF230"])), (_l()(), i1.ɵeld(8, 0, null, null, 5, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(9, 0, null, null, 4, "div", [["class", "input-group"]], null, null, null, null, null)), (_l()(), i1.ɵeld(10, 0, null, null, 2, "div", [["class", "input-group-prepend"]], null, null, null, null, null)), (_l()(), i1.ɵeld(11, 0, null, null, 1, "span", [["class", "input-group-text"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["@"])), (_l()(), i1.ɵeld(13, 0, null, null, 0, "input", [["class", "form-control mr-md-2"], ["placeholder", "T\u00ECm ki\u1EBFm"], ["type", "text"]], null, null, null, null, null)), (_l()(), i1.ɵeld(14, 0, null, null, 22, "div", [["class", "col-6"]], null, null, null, null, null)), (_l()(), i1.ɵeld(15, 0, null, null, 21, "div", [["class", "topbar-right"]], null, null, null, null, null)), (_l()(), i1.ɵeld(16, 0, null, null, 20, "ul", [], null, null, null, null, null)), (_l()(), i1.ɵeld(17, 0, null, null, 3, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(18, 0, null, null, 1, "i", [["class", "fa"], ["style", "font-size:24px; margin-right: 7px; color: black"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF2BE"])), (_l()(), i1.ɵted(-1, null, [" Account"])), (_l()(), i1.ɵeld(21, 0, null, null, 1, "li", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["Trang ch\u1EE7"])), (_l()(), i1.ɵeld(23, 0, null, null, 1, "li", [], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["T\u1EA1o"])), (_l()(), i1.ɵeld(25, 0, null, null, 6, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(26, 0, null, null, 1, "i", [["class", "fa icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF0C0"])), (_l()(), i1.ɵeld(28, 0, null, null, 1, "i", [["class", "fab icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF39F"])), (_l()(), i1.ɵeld(30, 0, null, null, 1, "i", [["class", "fas icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF0F3"])), (_l()(), i1.ɵeld(32, 0, null, null, 4, "li", [], null, null, null, null, null)), (_l()(), i1.ɵeld(33, 0, null, null, 1, "i", [["class", "fas icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uF51C"])), (_l()(), i1.ɵeld(35, 0, null, null, 1, "i", [["class", "material-icons icon-right"]], null, null, null, null, null)), (_l()(), i1.ɵted(-1, null, ["\uE887"]))], null, null); }
exports.View_TopbarComponent_0 = View_TopbarComponent_0;
function View_TopbarComponent_Host_0(_l) { return i1.ɵvid(0, [(_l()(), i1.ɵeld(0, 0, null, null, 1, "app-topbar", [], null, null, null, View_TopbarComponent_0, RenderType_TopbarComponent)), i1.ɵdid(1, 114688, null, 0, i2.TopbarComponent, [], null, null)], function (_ck, _v) { _ck(_v, 1, 0); }, null); }
exports.View_TopbarComponent_Host_0 = View_TopbarComponent_Host_0;
var TopbarComponentNgFactory = i1.ɵccf("app-topbar", i2.TopbarComponent, View_TopbarComponent_Host_0, {}, {}, []);
exports.TopbarComponentNgFactory = TopbarComponentNgFactory;


/***/ }),

/***/ "./src/app/topbar/topbar.component.scss.shim.ngstyle.js":
/*!**************************************************************!*\
  !*** ./src/app/topbar/topbar.component.scss.shim.ngstyle.js ***!
  \**************************************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

/**
 * @fileoverview This file was generated by the Angular template compiler. Do not edit.
 *
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride,checkTypes}
 * tslint:disable
 */ 
Object.defineProperty(exports, "__esModule", { value: true });
var styles = ["section[_ngcontent-%COMP%] {\n  width: 100%;\n  height: 50px;\n  background: #4267B2; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%] {\n    width: 100%;\n    height: 100%;\n    margin: 0; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%] {\n      display: flex;\n      justify-content: flex-end; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n        bottom: 0;\n        left: 0;\n        margin: 0;\n        padding: 0;\n        width: 80%;\n        height: 50px;\n        display: flex; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n        position: relative;\n        list-style: none;\n        width: 20%;\n        height: 50%;\n        display: flex;\n        align-items: center;\n        justify-content: center;\n        margin-top: auto;\n        margin-bottom: auto; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   .icon-right[_ngcontent-%COMP%] {\n          font-size: 28px;\n          color: white;\n          margin-right: 17px; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(1) {\n        width: 10%; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-left[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(2) {\n        width: 90%; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%] {\n      display: flex;\n      justify-content: flex-end; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%] {\n        bottom: 0;\n        left: 0;\n        margin: 0;\n        padding: 0;\n        width: 80%;\n        height: 50px;\n        display: flex; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%] {\n        font-weight: bold;\n        color: white;\n        font-size: 16px;\n        position: relative;\n        list-style: none;\n        width: 20%;\n        height: 50%;\n        display: flex;\n        align-items: center;\n        justify-content: center;\n        border-right: 0.5px solid;\n        margin-top: auto;\n        margin-bottom: auto;\n        border-color: #d6d6c2; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   .icon-right[_ngcontent-%COMP%] {\n          font-size: 22px;\n          color: #404040;\n          margin-right: 17px; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]   .icon-right[_ngcontent-%COMP%]:hover {\n          color: #000000;\n          cursor: pointer; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(1):hover, section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(2):hover, section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(3):hover {\n        background: #3B5CA0;\n        cursor: pointer; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(3) {\n        width: 10%; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(4) {\n        width: 25%; }\n  section[_ngcontent-%COMP%]   .row[_ngcontent-%COMP%]   .topbar-right[_ngcontent-%COMP%]   ul[_ngcontent-%COMP%]   li[_ngcontent-%COMP%]:nth-child(5) {\n        border: none; }\n/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbInNyYy9hcHAvdG9wYmFyL0M6XFxVc2Vyc1xcVnVOSFRcXERlc2t0b3BcXHRlc3RQcm9qZWN0XFx0ZXN0LWNvbnNvbGUvc3JjXFxhcHBcXHRvcGJhclxcdG9wYmFyLmNvbXBvbmVudC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBO0VBQ0ksWUFBVztFQUNYLGFBQVk7RUFDWixvQkFBbUIsRUErRnRCO0VBbEdEO0lBS1EsWUFBVztJQUNWLGFBQVk7SUFDWixVQUFTLEVBMEZqQjtFQWpHRDtNQVNRLGNBQWE7TUFDYiwwQkFBeUIsRUFpQzVCO0VBM0NMO1FBWVksVUFBUztRQUNULFFBQU87UUFDUCxVQUFTO1FBQ1QsV0FBVTtRQUNWLFdBQVU7UUFDVixhQUFZO1FBQ1osY0FBYSxFQUNoQjtFQW5CVDtRQXFCZ0IsbUJBQWtCO1FBQ2xCLGlCQUFnQjtRQUNoQixXQUFVO1FBQ1YsWUFBVztRQUNYLGNBQWE7UUFDYixvQkFBbUI7UUFDbkIsd0JBQXVCO1FBQ3ZCLGlCQUFnQjtRQUNoQixvQkFBbUIsRUFNdEI7RUFuQ2I7VUErQm9CLGdCQUFjO1VBQ2QsYUFBWTtVQUNaLG1CQUNGLEVBQUM7RUFsQ25CO1FBcUNnQixXQUFVLEVBQ1g7RUF0Q2Y7UUF3Q2dCLFdBQVUsRUFDWDtFQXpDZjtNQTZDUSxjQUFhO01BQ2IsMEJBQXlCLEVBa0Q1QjtFQWhHTDtRQWdEUSxVQUFTO1FBQ1QsUUFBTztRQUNQLFVBQVM7UUFDVCxXQUFVO1FBQ1YsV0FBVTtRQUNWLGFBQVk7UUFDWixjQUFhLEVBQ2Q7RUF2RFA7UUF5RFEsa0JBQWlCO1FBQ2pCLGFBQVk7UUFDWixnQkFBZTtRQUNmLG1CQUFrQjtRQUNsQixpQkFBZ0I7UUFDaEIsV0FBVTtRQUNWLFlBQVc7UUFDWCxjQUFhO1FBQ2Isb0JBQW1CO1FBQ25CLHdCQUF1QjtRQUN2QiwwQkFBMEI7UUFDNUIsaUJBQWdCO1FBQ2hCLG9CQUFtQjtRQUNuQixzQkFBcUIsRUFVcEI7RUFoRlA7VUF3RVEsZ0JBQWM7VUFDZCxlQUFjO1VBQ2QsbUJBQ0YsRUFBQztFQTNFUDtVQTZFUSxlQUFjO1VBQ2QsZ0JBQWUsRUFDaEI7RUEvRVA7OztRQW9GUSxvQkFBbUI7UUFDbkIsZ0JBQWUsRUFDaEI7RUF0RlA7UUF3RlEsV0FBVSxFQUNYO0VBekZQO1FBMkZRLFdBQVUsRUFDWDtFQTVGUDtRQThGUSxhQUFZLEVBQ2IiLCJmaWxlIjoic3JjL2FwcC90b3BiYXIvdG9wYmFyLmNvbXBvbmVudC5zY3NzIiwic291cmNlc0NvbnRlbnQiOlsic2VjdGlvbiB7XHJcbiAgICB3aWR0aDogMTAwJTtcclxuICAgIGhlaWdodDogNTBweDtcclxuICAgIGJhY2tncm91bmQ6ICM0MjY3QjI7XHJcbiAgICAucm93IHtcclxuICAgICAgICB3aWR0aDogMTAwJTtcclxuICAgICAgICAgaGVpZ2h0OiAxMDAlO1xyXG4gICAgICAgICBtYXJnaW46IDA7XHJcbiAgICAudG9wYmFyLWxlZnQge1xyXG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBmbGV4LWVuZDtcclxuICAgICAgICB1bCB7XHJcbiAgICAgICAgICAgIGJvdHRvbTogMDtcclxuICAgICAgICAgICAgbGVmdDogMDtcclxuICAgICAgICAgICAgbWFyZ2luOiAwO1xyXG4gICAgICAgICAgICBwYWRkaW5nOiAwO1xyXG4gICAgICAgICAgICB3aWR0aDogODAlO1xyXG4gICAgICAgICAgICBoZWlnaHQ6IDUwcHg7XHJcbiAgICAgICAgICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICAgICAgfVxyXG4gICAgICAgICAgIHVsIGxpIHtcclxuICAgICAgICAgICAgICAgIHBvc2l0aW9uOiByZWxhdGl2ZTtcclxuICAgICAgICAgICAgICAgIGxpc3Qtc3R5bGU6IG5vbmU7XHJcbiAgICAgICAgICAgICAgICB3aWR0aDogMjAlO1xyXG4gICAgICAgICAgICAgICAgaGVpZ2h0OiA1MCU7XHJcbiAgICAgICAgICAgICAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgICAgICAgICAgICAgYWxpZ24taXRlbXM6IGNlbnRlcjtcclxuICAgICAgICAgICAgICAgIGp1c3RpZnktY29udGVudDogY2VudGVyO1xyXG4gICAgICAgICAgICAgICAgbWFyZ2luLXRvcDogYXV0bztcclxuICAgICAgICAgICAgICAgIG1hcmdpbi1ib3R0b206IGF1dG87XHJcbiAgICAgICAgICAgICAgICAuaWNvbi1yaWdodCB7XHJcbiAgICAgICAgICAgICAgICAgICAgZm9udC1zaXplOjI4cHg7IFxyXG4gICAgICAgICAgICAgICAgICAgIGNvbG9yOiB3aGl0ZTsgXHJcbiAgICAgICAgICAgICAgICAgICAgbWFyZ2luLXJpZ2h0OiAxN3B4IFxyXG4gICAgICAgICAgICAgICAgICB9XHJcbiAgICAgICAgICAgIH1cclxuICAgICAgICAgICAgdWwgbGk6bnRoLWNoaWxkKDEpIHtcclxuICAgICAgICAgICAgICAgIHdpZHRoOiAxMCU7XHJcbiAgICAgICAgICAgICAgfVxyXG4gICAgICAgICAgICAgIHVsIGxpOm50aC1jaGlsZCgyKSB7XHJcbiAgICAgICAgICAgICAgICB3aWR0aDogOTAlO1xyXG4gICAgICAgICAgICAgIH1cclxuICAgICAgICAgIFxyXG4gICAgfVxyXG4gICAgLnRvcGJhci1yaWdodCB7XHJcbiAgICAgICAgZGlzcGxheTogZmxleDtcclxuICAgICAgICBqdXN0aWZ5LWNvbnRlbnQ6IGZsZXgtZW5kO1xyXG4gICAgdWwge1xyXG4gICAgICAgIGJvdHRvbTogMDtcclxuICAgICAgICBsZWZ0OiAwO1xyXG4gICAgICAgIG1hcmdpbjogMDtcclxuICAgICAgICBwYWRkaW5nOiAwO1xyXG4gICAgICAgIHdpZHRoOiA4MCU7XHJcbiAgICAgICAgaGVpZ2h0OiA1MHB4O1xyXG4gICAgICAgIGRpc3BsYXk6IGZsZXg7XHJcbiAgICAgIH1cclxuICAgICAgdWwgbGkge1xyXG4gICAgICAgIGZvbnQtd2VpZ2h0OiBib2xkO1xyXG4gICAgICAgIGNvbG9yOiB3aGl0ZTtcclxuICAgICAgICBmb250LXNpemU6IDE2cHg7XHJcbiAgICAgICAgcG9zaXRpb246IHJlbGF0aXZlO1xyXG4gICAgICAgIGxpc3Qtc3R5bGU6IG5vbmU7XHJcbiAgICAgICAgd2lkdGg6IDIwJTtcclxuICAgICAgICBoZWlnaHQ6IDUwJTtcclxuICAgICAgICBkaXNwbGF5OiBmbGV4O1xyXG4gICAgICAgIGFsaWduLWl0ZW1zOiBjZW50ZXI7XHJcbiAgICAgICAganVzdGlmeS1jb250ZW50OiBjZW50ZXI7XHJcbiAgICAgICAgYm9yZGVyLXJpZ2h0OiAwLjVweCBzb2xpZCA7XHJcbiAgICAgIG1hcmdpbi10b3A6IGF1dG87XHJcbiAgICAgIG1hcmdpbi1ib3R0b206IGF1dG87XHJcbiAgICAgIGJvcmRlci1jb2xvcjogI2Q2ZDZjMjtcclxuICAgICAgLmljb24tcmlnaHQge1xyXG4gICAgICAgIGZvbnQtc2l6ZToyMnB4OyBcclxuICAgICAgICBjb2xvcjogIzQwNDA0MDsgXHJcbiAgICAgICAgbWFyZ2luLXJpZ2h0OiAxN3B4IFxyXG4gICAgICB9XHJcbiAgICAgIC5pY29uLXJpZ2h0OmhvdmVyIHtcclxuICAgICAgICBjb2xvcjogIzAwMDAwMDtcclxuICAgICAgICBjdXJzb3I6IHBvaW50ZXI7XHJcbiAgICAgIH1cclxuICAgICAgfVxyXG4gICAgICB1bCBsaTpudGgtY2hpbGQoMSk6aG92ZXIsXHJcbiAgICAgIHVsIGxpOm50aC1jaGlsZCgyKTpob3ZlcixcclxuICAgICAgdWwgbGk6bnRoLWNoaWxkKDMpOmhvdmVyIHtcclxuICAgICAgICBiYWNrZ3JvdW5kOiAjM0I1Q0EwO1xyXG4gICAgICAgIGN1cnNvcjogcG9pbnRlcjtcclxuICAgICAgfVxyXG4gICAgICB1bCBsaTpudGgtY2hpbGQoMykge1xyXG4gICAgICAgIHdpZHRoOiAxMCU7XHJcbiAgICAgIH1cclxuICAgICAgdWwgbGk6bnRoLWNoaWxkKDQpIHtcclxuICAgICAgICB3aWR0aDogMjUlO1xyXG4gICAgICB9XHJcbiAgICAgIHVsIGxpOm50aC1jaGlsZCg1KSB7XHJcbiAgICAgICAgYm9yZGVyOiBub25lO1xyXG4gICAgICB9XHJcbiAgICB9XHJcbn1cclxufSJdfQ== */"];
exports.styles = styles;


/***/ }),

/***/ "./src/app/topbar/topbar.component.ts":
/*!********************************************!*\
  !*** ./src/app/topbar/topbar.component.ts ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var TopbarComponent = /** @class */ (function () {
    function TopbarComponent() {
    }
    TopbarComponent.prototype.ngOnInit = function () {
    };
    return TopbarComponent;
}());
exports.TopbarComponent = TopbarComponent;


/***/ }),

/***/ "./src/environments/environment.ts":
/*!*****************************************!*\
  !*** ./src/environments/environment.ts ***!
  \*****************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
exports.environment = {
    production: true,
    baseHref: '/production/',
    SLS_DEBUG: '*'
};


/***/ }),

/***/ "./src/main.server.ts":
/*!****************************!*\
  !*** ./src/main.server.ts ***!
  \****************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

"use strict";

Object.defineProperty(exports, "__esModule", { value: true });
var app_server_module_ngfactory_1 = __webpack_require__(/*! ./app/app.server.module.ngfactory */ "./src/app/app.server.module.ngfactory.js");
exports.AppServerModuleNgFactory = app_server_module_ngfactory_1.AppServerModuleNgFactory;
var core_1 = __webpack_require__(/*! @angular/core */ "@angular/core");
var environment_1 = __webpack_require__(/*! ./environments/environment */ "./src/environments/environment.ts");
if (environment_1.environment.production) {
    core_1.enableProdMode();
}
var app_server_module_1 = __webpack_require__(/*! ./app/app.server.module */ "./src/app/app.server.module.ts");
exports.AppServerModule = app_server_module_1.AppServerModule;
exports.LAZY_MODULE_MAP = {};


/***/ }),

/***/ 0:
/*!**********************************!*\
  !*** multi ./src/main.server.ts ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

module.exports = __webpack_require__(/*! C:\Users\VuNHT\Desktop\testProject\test-console\src\main.server.ts */"./src/main.server.ts");


/***/ }),

/***/ "@angular/animations":
/*!**************************************!*\
  !*** external "@angular/animations" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations");

/***/ }),

/***/ "@angular/animations/browser":
/*!**********************************************!*\
  !*** external "@angular/animations/browser" ***!
  \**********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/animations/browser");

/***/ }),

/***/ "@angular/common":
/*!**********************************!*\
  !*** external "@angular/common" ***!
  \**********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common");

/***/ }),

/***/ "@angular/common/http":
/*!***************************************!*\
  !*** external "@angular/common/http" ***!
  \***************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/common/http");

/***/ }),

/***/ "@angular/core":
/*!********************************!*\
  !*** external "@angular/core" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/core");

/***/ }),

/***/ "@angular/http":
/*!********************************!*\
  !*** external "@angular/http" ***!
  \********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/http");

/***/ }),

/***/ "@angular/platform-browser":
/*!********************************************!*\
  !*** external "@angular/platform-browser" ***!
  \********************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser");

/***/ }),

/***/ "@angular/platform-browser/animations":
/*!*******************************************************!*\
  !*** external "@angular/platform-browser/animations" ***!
  \*******************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-browser/animations");

/***/ }),

/***/ "@angular/platform-server":
/*!*******************************************!*\
  !*** external "@angular/platform-server" ***!
  \*******************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@angular/platform-server");

/***/ }),

/***/ "@ng-toolkit/universal":
/*!****************************************!*\
  !*** external "@ng-toolkit/universal" ***!
  \****************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@ng-toolkit/universal");

/***/ }),

/***/ "@nguniversal/common":
/*!**************************************!*\
  !*** external "@nguniversal/common" ***!
  \**************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/common");

/***/ }),

/***/ "@nguniversal/module-map-ngfactory-loader":
/*!***********************************************************!*\
  !*** external "@nguniversal/module-map-ngfactory-loader" ***!
  \***********************************************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("@nguniversal/module-map-ngfactory-loader");

/***/ }),

/***/ "rxjs/operators":
/*!*********************************!*\
  !*** external "rxjs/operators" ***!
  \*********************************/
/*! no static exports found */
/***/ (function(module, exports) {

module.exports = require("rxjs/operators");

/***/ })

/******/ })));
//# sourceMappingURL=main.js.map